version: "3.9"

services:
  web:
    build: .
    container_name: car-park-web
    # command: gunicorn car_park.wsgi:application --bind 0.0.0.0:8000
    # for local test
    #    command: >
    #      bash -c "
    #      python manage.py migrate &&
    #      python manage.py runserver 0.0.0.0:8000
    #      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env
    # for local test
    #    ports:
    #      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.5
    container_name: car-park-db
    restart: unless-stopped
    env_file:
      - .env
    # for local test
    #    ports:
    #      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.25-alpine
    container_name: car-park-nginx
    restart: unless-stopped
    ports:
      - "80:80"        # public port
    depends_on:
      - web
    volumes:
      - static_volume:/app/staticfiles:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  static_volume: