# Generated by Django 5.1.1 on 2024-09-24 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_brand_configuration_alter_vehicle_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='tank_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Объем бака (л)'),
        ),
    ]
