# Generated by Django 5.1.1 on 2025-01-04 16:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_enterprise_local_timezone_vehicle_purchase_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleGPSPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'GPS точка автомобиля',
                'verbose_name_plural': 'GPS точки автомобилей',
                'ordering': ['timestamp'],
            },
        ),
    ]
