# Generated by Django 5.1.1 on 2025-01-25 20:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='route',
            name='start_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
